#!/usr/bin/env php
<?php

declare(strict_types=1);

use Andriichuk\Enviro\Application\Command\AddCommand;
use Andriichuk\Enviro\Application\Command\FillCommand;
use Andriichuk\Enviro\Application\Command\InitCommand;
use Andriichuk\Enviro\Application\Command\VerifyCommand;
use Dotenv\Dotenv;
use Symfony\Component\Console\Application;

require_once 'vendor/autoload.php';

$dotenv = Dotenv::createImmutable(__DIR__ . '/stubs');
$dotenv->load();

$application = new Application();
$application->add(new InitCommand());
$application->add(new VerifyCommand());
$application->add(new AddCommand());
$application->add(new FillCommand());
$application->run();
