#!/usr/bin/env php
<?php

declare(strict_types=1);

use Andriichuk\EnvValidator\Application\Command\VerifyCommand;
use Dotenv\Dotenv;
use Symfony\Component\Console\Application;

require_once 'vendor/autoload.php';

$dotenv = Dotenv::createImmutable(__DIR__ . '/stubs');
$dotenv->load();

$application = new Application();
$application->add(new VerifyCommand());
$application->run();
